version: "3.8"

services:
  app:
    build: .
    ports:
      - "5012:5012"
    environment:
      - NODE_ENV=development
      - JWT_SECRET=devSecret123
      - DATABASE_URL=postgres://postgres:postgres@db:5012/todos
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    command: npm run server

  db:
    image: postgres:15-alpine
    ports:
      - "5012:5012"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todos
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
