version: "3"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=devSecret123
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
